Switch to yml issue templates
EarthMC/Issue-Tracker pull request #1440
Opened 2021-12-05 07:29 UTC by Basically-Andrew

2021-12-05 15:54 UTC, KarlOfDuty commented
![image](https://media2.giphy.com/media/s239QJIh56sRW/giphy.gif)

2021-12-05 16:07 UTC, Basically-Andrew commented
Switching to yml issue templates allow players less familiar with Github to create an issue using Github's text areas. Its clean and simple for every user to create an issue with this on Github.
![image](https://user-images.githubusercontent.com/59465284/144754028-eb7a3b67-5240-4307-ad32-d5b32b45583c.png)

2021-12-05 16:25 UTC, Warriorrrr requested changes

2021-12-05 16:25 UTC, Warriorrrr commented on .github/ISSUE_TEMPLATE/bug_report.yml
> +    placeholder: "Which server the bug is on."
Don't use placeholder, use description instead. Needs to be done for all fields.

2021-12-05 16:25 UTC, Warriorrrr commented on .github/ISSUE_TEMPLATE/feature_request.yml
> +    placeholder: "A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]"
Same here

2021-12-05 17:06 UTC, Basically-Andrew commented
Thanks, for all fields I've moved from placeholder to description instead.

2022-01-07 20:41 UTC, Warriorrrr approved these changes

2022-01-07 20:41 UTC, merged